### ISSUE TITLE
Latest branch (3.3.0.814) Missing Summarize.xslt

### ISSUE THREAD

**Issue by edimusrex** [Arelle/EdgarRenderer#2]
I noticed that the latest release of the previewer no longer has the Summarize.xslt file.  On our testing environment the previewer refuses to run with out this file.  I have updated out environment to include the Summarize.xslt file from master which seems to have fixed the issue.  Is there a reason this file is now gone?

**Comment by hamscher** [comment]
Just an oversight, sorry.  It will be reinstated.  Thanks/w

**Comment by edimusrex** [comment]
OK, thank you.  Was just making sure something hadn’t changed with the previewer.

 

Ed Dunn | Systems/Security Administrator

CompSci Resources, LLC
T: 703.750.3232
F: 703.750.3613

5520 Cherokee Avenue, Suite 230
Alexandria, VA 22312
www.compsciresources.com
 <http://www.compsciresources.com/> CompSciResources

**Comment by hamscher** [comment]
Issue should be closed.
